version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: openrun-local-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=openrun
      - POSTGRES_PASSWORD=openrun123#
    ports:
      - "5432:5432"
    volumes:
      - postgres-local-data:/var/lib/postgresql/data

volumes:
  postgres-local-data:
    driver: local
