spring:
  # MariaDB 설정
  datasource:
    url: jdbc:mariadb://dev-db:3306/openrun
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Neo4j 설정
  neo4j:
    uri: bolt://dev-neo4j:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    connection:
      pool:
        max-connection-lifetime: 1h
        max-connection-pool-size: 100

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 로깅 설정
logging:
  level:
    root: INFO
    com.example.openrunapi: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
