# ===============================
# JPA & HIBERNATE
# ===============================
# ddl-auto: none(or validate) - Do not automatically create or update the schema. Let Flyway handle it.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
# Location of the migration scripts
spring.flyway.locations=classpath:db/migration
